version: 2

models:
  - name: dim_listings_with_hosts
    description: "DIM listings with hosts"
    columns:
      - name: listing_id
        data_tests:
          - unique
          - not_null
      - name: host_id
        data_tests:
          - not_null
          - relationships:
              field: host_id
              to: ref('src_hosts')

  - name: fact_reviews
    description: "Fact reviews table"
    columns:
      - name: listing_id
        data_tests:
          - not_null
          - relationships:
              field: listing_id
              to: ref('src_listings')

  - name: dim_emp_dept_dtls_hist
    description: "Employee with Department details"
    columns:
      - name: emp_sk
        description: "Primary key for DIM_EMP_DEPT_DTLS_HIST  table"
        data_tests:
          - unique
          - not_null
      - name: emp_id
        description: "Employee ID"
        data_tests:
          - not_null

  - name: dim_listings_cleansed
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null
      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        tests:
          - accepted_values:
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]

  - name: src_emp
    columns:
      - name: commission
        description: "Commission received"
        tests:
          - assert_between:
              min_value: 0
              max_value: 2500
